### PR TITLE
#486 portfolio react query refactor

### LINKED ISSUE #486: Refactor portfolio page to use react-query for remote data fetching.
**Tasks:**
- [ ] Refactor the portfolio page to use react query for data fetching.
- [ ] Bonus: reuse/refactor existing query hooks for more reusability and data caching performance gains.

### PR DESCRIPTION
**Pull request by yornaath**
Fixes #486

### CODE REVIEW

**Review by TvrtkoM — COMMENTED** [review]
It takes some time to show portfolio tables on first load. Can some kind of loading indicator be added, or skeletons?

**Comment by TvrtkoM** [comment]
Trade (buy/sell) buttons are no longer visible on market details page
https://ui-2my5lbf2w-zeitgeistpm.vercel.app/markets/367

they are visible on staging
https://staging.zeitgeist.pm/markets/367

**Comment by yornaath** [comment]
> 

This market is now broken in staging also stuck at loading.

**Comment by TvrtkoM** [comment]
@yornaath I'm able to open the link. the buy / sell buttons show sometimes, but most of the time, especially when landing on market details page they are not showing up

**Comment by yornaath** [comment]
> @yornaath I'm able to open the link. the buy / sell buttons show sometimes, but most of the time, especially when landing on market details page they are not showing up

Meaning sometimes they show and sometimes they dont even for the same markets? And most often when going to the market details page? Which markets should I test?

**Comment by TvrtkoM** [comment]
> > @yornaath I'm able to open the link. the buy / sell buttons show sometimes, but most of the time, especially when landing on market details page they are not showing up
> 
> Meaning sometimes they show and sometimes they dont even for the same markets? And most often when going to the market details page? Which markets should I test?

Any active market. What I've noticed is buy / sell buttons only show up when I go to market page by clicking on market card on `/markets` page. If I go directly to this link e.g. https://ui-2my5lbf2w-zeitgeistpm.vercel.app/markets/367 there are no buy / sell buttons (they how up here https://staging.zeitgeist.pm/markets/367)

**Comment by yornaath** [comment]
Can you test again @TvrtkoM? I think it should be fixed now.

**Comment by TvrtkoM** [comment]
The following happens for categorical markets:

- reported market's details page doesn't open (made a fix here https://github.com/zeitgeistpm/ui/pull/489/commits/19d57dad380e10372600ec4195119d71cf4b9a1c)
- dispting a market throws error - `DisputeButton.tsx` line 65 - ` TypeError: Cannot read properties of undefined (reading '1')`
 
The following happens for scalar markets:
- after disputing scalar markets, buy/sell buttons show on market details page, they shouldn't show up. We used to show report buttons if authority address is selected in wallet (or its proxies).

**Pull request closed without merging**
