### PR TITLE
New modals

### PR DESCRIPTION
**Pull request by Robiquet**

### CODE REVIEW

**Review by robhyrk — CHANGES_REQUESTED** [review]
I did a couple tests locally to try it out, and it all looks good to me. Might be helpful to get another set of eyes though to be sure as there were quite a few changes.

**Comment by robhyrk** [comment]
One finer detail that is UX related; if the user has 0 ZTG the UX could be improved a bit I feel. It might be helpful to have some sort of message/CTA to let the user know where they might be able to get some ZTG 

Screenshot 2023-03-02 at 6 46 45 PM

**Review by TvrtkoM — APPROVED** [review]
there is an error in the console
`Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?` when share dialog shows up (TwitterBird). Other than that, LG

**Comment by Robiquet** [comment]
> One finer detail that is UX related; if the user has 0 ZTG the UX could be improved a bit I feel. It might be helpful to have some sort of message/CTA to let the user know where they might be able to get some ZTG
> 
> Screenshot 2023-03-02 at 6 46 45 PM

Sure, we can add a design ticket for this

**Review by robhyrk — APPROVED** [review]

**Comment by robhyrk** [comment]
closes #605

**Pull request merged**
