### PR TITLE
allow market creators to specify timezone

### PR DESCRIPTION
**Pull request by TvrtkoM**
#266

### CODE REVIEW

**Comment by Robiquet** [comment]
Is it possible to default to local timezone with something like `new Date().getTimezoneOffset()`? @mk26071980 could you provide a design for this?

**Comment by TvrtkoM** [comment]
> Is it possible to default to local timezone with something like `new Date().getTimezoneOffset()`? @mk26071980 could you provide a design for this?

it is possible with `moment.tz.guess()` but the issue mentiones the default should be UTC

**Review by Robiquet — COMMENTED** [review]
Seems like something strange has happened to the drop downs.

Looked like this before:
image

Now it looks like:
image

**Review by Robiquet — APPROVED** [review]
Actually ignore the above, looks like just a safari thing

**Pull request merged**
