### PR TITLE
Portfolio account switch

### LINKED ISSUE #1236: Changing selected account on portfolio page should reload portfolio with new account

### PR DESCRIPTION
**Pull request by TvrtkoM**
close #1236

### CODE REVIEW

**Review by Robiquet — COMMENTED** [review]
Not too sure how it happened but I got this error when switching between accounts 
image

**Comment by TvrtkoM** [comment]
> Not too sure how it happened but I got this error when switching between accounts image

Can't reproduce it

**Comment by TvrtkoM** [comment]
> I think we should still support account sharing if there is a connected wallet. For example if I click the link on the market page I get redirected to the connected wallet isn't of the one in the link I clicked image

You're right this should work, but what happens if i change the account now?
e.g. my wallet is connected and, open Malte's portfolio and now I switch account in my wallet. Think I should still be on Malte's portfolio page

**Comment by Robiquet** [comment]
> update portfolio account switching

yeah that sounds right to me

**Comment by Robiquet** [comment]
> > Not too sure how it happened but I got this error when switching between accounts image
> 
> Can't reproduce it

I've pushed a fix

**Review by Robiquet — APPROVED** [review]

**Pull request merged**
