### PR TITLE
Improve proxy settings UX

### LINKED ISSUE #1880: UX for proxy accounts may be misleading
user can't save when "Enable Proxy Execution" is checked and when the account is not a proxy

 
Screenshot 2023-10-11 at 10 49 14 PM

however, if you simply deselect the checkbox the user can now save these settings

Screenshot 2023-10-11 at 10 49 24 PM

### PR DESCRIPTION
**Pull request by yornaath**
Fixes #1880

### CODE REVIEW

**Review by robhyrk — COMMENTED** [review]
Is it possible to disable the save button when 'Enable Proxy Execution' is disabled after being enabled?

Screenshot 2023-10-19 at 11 07 25 AM

**Review by Robiquet — APPROVED** [review]
Thanks!

**Review by robhyrk — APPROVED** [review]
Looks great!

**Review by robhyrk — APPROVED** [review]
disregard previous comment; looks good!

**Pull request merged**
