### PR TITLE
Grillchat

### PR DESCRIPTION
**Pull request by TvrtkoM**
#715

### CODE REVIEW

**Comment by Robiquet** [comment]
@mk26071980 do you have a icon to replace this with? 
image

**Comment by Robiquet** [comment]
I think the background should be solid 
image

**Comment by Robiquet** [comment]
Seeing this now, did that change overwrite the whole thing?
image

**Comment by TvrtkoM** [comment]
@Robiquet it seems it was an issue with grillchat. It is working now

**Review by Robiquet — APPROVED** [review]

**Pull request merged**
