### PR TITLE
Multi asset support 1

### PR DESCRIPTION
**Pull request by Robiquet**

### CODE REVIEW

**Comment by Robiquet** [comment]
Still some todo comments, but might be worth getting this review and merged now before it gets too big

**Comment by Robiquet** [comment]
Seems like I've introduced a performance related to the slider on `ExitPoolForm`. Trying to figure out what it is

**Comment by Robiquet** [comment]
> Seems like I've introduced a performance issue related to the slider on `ExitPoolForm`. Trying to figure out what it is

Doesn't look related to this pr, fix is here https://github.com/zeitgeistpm/ui/pull/1095

**Review by TvrtkoM — APPROVED** [review]
lgtm

**Pull request merged**
