### PR TITLE
change numbers to mono

### LINKED ISSUE #1618: Number should be mono
All numbers in the app should be roboto mono

### PR DESCRIPTION
**Pull request by TvrtkoM**
close #1618

### CODE REVIEW

**Comment by yornaath** [comment]
Numbers are white when market cards are hovered?
Screenshot 2023-08-21 at 09 58 50

**Comment by mk26071980** [comment]
Im changing it all to mono.

**Comment by TvrtkoM** [comment]
> Im changing it all to mono.

I'm closing this PR until we know which ui elements need mono font

**Comment by mk26071980** [comment]
Changed the numerical. https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?type=design&node-id=6790%3A482&mode=design&t=aKobFPqRacvTD0w9-1

**Pull request closed without merging**
