### PR TITLE
Create account & deposit pages

### LINKED ISSUE #1611: Create Account page

### PR DESCRIPTION
**Pull request by TvrtkoM**
close #1611

### CODE REVIEW

**Comment by yornaath** [comment]
Screenshot 2023-08-16 at 12 30 55
Screenshot 2023-08-16 at 12 31 39
Screenshot 2023-08-16 at 12 32 56

**Comment by TvrtkoM** [comment]
> Screenshot 2023-08-16 at 12 31 39

Design is that way. There is additional UI for DOT since it can be moved from Polkadot to Zeitgeist chain. For ZTG user usually deposits crypto from exchange to given wallet address.

Other remarks are fixed

**Comment by yornaath** [comment]
Some issues with the links on the deposit page:

 Buy -> Dot
   -> Credit card -> Banxa _(just opens the deposit page in a new tab)_
   -> Crypto -> Dex _(just opens the deposit page in a new tab)_
   -> Crypto -> Dex _(just opens the deposit page in a new tab)_
   -> Crypto -> Cex _(just opens the deposit page in a new tab)_

**Comment by lsaether** [comment]
Can you add hover effects to the buttons and the cards at the bottom?

**Comment by yornaath** [comment]
Should these buttons have the same hover effect as on the create account page?
Screenshot 2023-08-21 at 09 57 15

**Comment by mk26071980** [comment]
If DOT is chosen all the copy should be related to dot, of course. I'll fix the copy in the designs if needed.

**Review by yornaath — APPROVED** [review]

**Pull request merged**
